// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0

package common

import "github.com/omec-project/gnbsim/logger"

type EventType uint32

//type MsgType uint8

/* Using the MSB to represent the interface to which the event belongs.*/
const (
	/* Network interface events */
	UU_EVENT EventType = 0x1000000
	N1_EVENT EventType = 0x2000000
	N2_EVENT EventType = 0x3000000
	N3_EVENT EventType = 0x4000000

	/* Application's interfaces events */
	PROFILE_SIMUE_EVENT EventType = 0x5000000
	SIMUE_REALUE_EVENT  EventType = 0x6000000
	COMMON_EVENT        EventType = 0x7000000
	PROC_SIMUE_EVENT    EventType = 0x8000000
)

const (
	INIT_EVENT EventType = COMMON_EVENT + 1 + iota
	QUIT_EVENT
	ERROR_EVENT
)

const (
	PROC_START_EVENT EventType = PROC_SIMUE_EVENT + 1 + iota
	PROC_PASS_EVENT
	PROC_FAIL_EVENT
)

/* Events between SimUe and RealUE */
// Events built by the addition of N1_ENCODE_EVENT or N1_DECODED_EVENT and NAS_5GMM messages
const N1_ENCODE_EVENT EventType = N1_EVENT + 0x0100000
const N1_ENCODED_EVENT EventType = N1_EVENT + 0x0200000
const N1_DECODE_EVENT EventType = N1_EVENT + 0x0400000
const N1_DECODED_EVENT EventType = N1_EVENT + 0x0800000

const (
	DATA_PKT_GEN_REQUEST_EVENT EventType = SIMUE_REALUE_EVENT + 1 + iota
	DATA_PKT_GEN_SUCCESS_EVENT
	DATA_PKT_GEN_FAILURE_EVENT
	// Then all N1_ENCODE_EVENT, N1_DECODED_EVENT events
)

/* Events between UE and GNodeB (UU) */
const (
	CONNECTION_REQUEST_EVENT EventType = UU_EVENT + 1 + iota
	CONNECTION_RELEASE_REQUEST_EVENT

	UL_INFO_TRANSFER_EVENT
	DL_INFO_TRANSFER_EVENT

	// For exchanging user data
	UL_UE_DATA_TRANSFER_EVENT
	DL_UE_DATA_TRANSFER_EVENT
	LAST_DATA_PKT_EVENT

	// For setting up channels between UE and GNB to exchange user data
	DATA_BEARER_SETUP_REQUEST_EVENT
	DATA_BEARER_SETUP_RESPONSE_EVENT
	DATA_BEARER_RELEASE_REQUEST_EVENT

	// gNB acknowledges simue for releasing UE context using this event
	CTX_RELEASE_ACKNOWLEDGEMENT_EVENT

	// SimUe commands gNB to trigger RAN Connection release which further
	// triggers gNB initiated UE Context Release Request
	TRIGGER_AN_RELEASE_EVENT
)

/* Events betweem UE and AMF (N1)
 * Following events offsets are numbered same as the NAS Message types in
 * section 9.7 of 3GPP TS 24.501. This makes it easy to generate events
 * corresponding to received NAS messages.
 */
//const UE_5GS_MOBILITY_MANAGEMENT_EVENTS EventType = N1_EVENT + 64
//const UE_5GS_SESSION_MANAGEMENT_EVENTS EventType = N1_EVENT + 192

const N1_SEND_SDU_EVENT EventType = N1_EVENT + 0x0010000
const N1_RECV_SDU_EVENT EventType = N1_EVENT + 0x0020000

// Message types for 5GS mobility management from NAS 3GPP specifications.
const (
	_                             EventType = 64 + iota
	NAS_5GMM_REGISTRATION_REQUEST           //65 = 0x41
	NAS_5GMM_REGISTRATION_ACCEPT
	NAS_5GMM_REGISTRATION_COMPLETE
	NAS_5GMM_REGISTRATION_REJECT
	NAS_5GMM_DEREGISTRATION_REQUEST_UE_ORIG
	NAS_5GMM_DEREGISTRATION_ACCEPT_UE_ORIG
	NAS_5GMM_DEREGISTRATION_REQUEST_UE_TERM
	NAS_5GMM_DEREGISTRATION_ACCEPT_UE_TERM //72 = 0x48
	_
	_
	_
	NAS_5GMM_SERVICE_REQUEST
	NAS_5GMM_SERVICE_REJECT
	NAS_5GMM_SERVICE_ACCEPT                //78
	NAS_5GMM_CONTROL_PLANE_SERVICE_REQUEST //79
	NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMMAND
	NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMPLETE
	NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_RESULT //82 =0x52
	_
	NAS_5GMM_CONFIGURATION_UPDATE
	NAS_5GMM_CONFIGURATION_UPDATE_COMPLETE
	NAS_5GMM_AUTHENTICATION_REQUEST // 0x56
	NAS_5GMM_AUTHENTICATION_RESPONSE
	NAS_5GMM_AUTHENTICATION_REJECT
	NAS_5GMM_AUTHENTICATION_FAILURE
	NAS_5GMM_AUTHENTICATION_RESULT
	NAS_5GMM_IDENTITY_REQUEST
	NAS_5GMM_IDENTITY_RESPONSE
	NAS_5GMM_SECURITY_MODE_COMMAND
	NAS_5GMM_SECURITY_MODE_COMPLETE
	NAS_5GMM_SECURITY_MODE_REJECT //95
	_
	_
	_
	_
	NAS_5GMM_STATUS //100
	NAS_5GMM_NOTIFICATION
	NAS_5GMM_NOTIFICATION_RESPONSE
	NAS_5GMM_UL_NAS_TRANSPORT
	NAS_5GMM_DL_NAS_TRANSPORT
)

// Message types for 5GS session management from NAS 3GPP specifications.
const (
	_                                          EventType = 128 + 64 + iota
	NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REQUEST           //193
	NAS_5GSM_PDU_SESSION_ESTABLISHMENT_ACCEPT
	NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REJECT // 195
	_
	NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMMAND // 197
	NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMPLETE
	NAS_5GSM_PDU_SESSION_AUTHENTICATION_RESULT // 199
	_
	_
	NAS_5GSM_PDU_SESSION_MODIFICATION_REQUEST // 201
	NAS_5GSM_PDU_SESSION_MODIFICATION_REJECT
	NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND
	NAS_5GSM_PDU_SESSION_MODIFICATION_COMPLETE
	NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_REJECT // 205
	_
	_
	_
	NAS_5GSM_PDU_SESSION_RELEASE_REQUEST // 209
	NAS_5GSM_PDU_SESSION_RELEASE_REJECT
	NAS_5GSM_PDU_SESSION_RELEASE_COMMAND
	NAS_5GSM_PDU_SESSION_RELEASE_COMPLETE // 212
	_
	_
	NAS_5GSM_STATUS //214
	_
	_
	NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMMAND //216
	NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMPLETE
	NAS_5GSM_REMOTE_UE_REPORT // 218
	NAS_5GSM_REMOTE_UE_REPORT_RESPONSE
)

// 5GS Mobility Management events.
// const (
// 	_                                        EventType = UE_5GS_MOBILITY_MANAGEMENT_EVENTS + iota
// 	NAS_5GMM_REGISTRATION_REQUEST_SEND_EVENT           //65
// 	NAS_5GMM_REGISTRATION_ACCEPT_RECV_EVENT
// 	NAS_5GMM_REGISTRATION_COMPLETE_SEND_EVENT
// 	NAS_5GMM_REGISTRATION_REJECT_RECV_EVENT
// 	NAS_5GMM_DEREGISTRATION_REQUEST_UE_ORIG_SEND_EVENT
// 	NAS_5GMM_DEREGISTRATION_ACCEPT_UE_ORIG_RECV_EVENT
// 	NAS_5GMM_DEREGISTRATION_REQUEST_UE_TERM_RECV_EVENT
// 	NAS_5GMM_DEREGISTRATION_ACCEPT_UE_TERM_SEND_EVENT //72
// 	_
// 	_
// 	_
// 	NAS_5GMM_SERVICE_REQUEST_SEND_EVENT
// 	NAS_5GMM_SERVICE_REJECT_RECV_EVENT
// 	NAS_5GMM_SERVICE_ACCEPT_RECV_EVENT                //78
// 	NAS_5GMM_CONTROL_PLANE_SERVICE_REQUEST_SEND_EVENT //79
// 	NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMMAND_RECV_EVENT
// 	NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMPLETE_SEND_EVENT
// 	NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_RESULT_RECV_EVENT //82
// 	_
// 	NAS_5GMM_CONFIGURATION_UPDATE_RECV_EVENT
// 	NAS_5GMM_CONFIGURATION_UPDATE_COMPLETE_SEND_EVENT
// 	NAS_5GMM_AUTHENTICATION_REQUEST_RECV_EVENT
// 	NAS_5GMM_AUTHENTICATION_RESPONSE_SEND_EVENT
// 	NAS_5GMM_AUTHENTICATION_REJECT_RECV_EVENT
// 	NAS_5GMM_AUTHENTICATION_FAILURE_SEND_EVENT
// 	NAS_5GMM_AUTHENTICATION_RESULT_RECV_EVENT
// 	NAS_5GMM_IDENTITY_REQUEST_RECV_EVENT
// 	NAS_5GMM_IDENTITY_RESPONSE_SEND_EVENT
// 	NAS_5GMM_SECURITY_MODE_COMMAND_RECV_EVENT
// 	NAS_5GMM_SECURITY_MODE_COMPLETE_SEND_EVENT
// 	NAS_5GMM_SECURITY_MODE_REJECT_SEND_EVENT //95
// 	_
// 	_
// 	_
// 	_
// 	NAS_5GMM_STATUS_SEND_EVENT //100
// 	NAS_5GMM_NOTIFICATION_RECV_EVENT
// 	NAS_5GMM_NOTIFICATION_RESPONSE_SEND_EVENT
// 	NAS_5GMM_UL_NAS_TRANSPORT_SEND_EVENT
// 	NAS_5GMM_DL_NAS_TRANSPORT_RECV_EVENT
// )

// 5GS Session Management events.
// const (
// 	_                                                     EventType = UE_5GS_SESSION_MANAGEMENT_EVENTS + iota
// 	NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REQUEST_SEND_EVENT           //193
// 	NAS_5GSM_PDU_SESSION_ESTABLISHMENT_ACCEPT_RECV_EVENT
// 	NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REJECT_RECV_EVENT

// 	NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMMAND_RECV_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 1 + iota
// 	NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMPLETE_SEND_EVENT
// 	NAS_5GSM_PDU_SESSION_AUTHENTICATION_RESULT_RECV_EVENT

// 	NAS_5GSM_PDU_SESSION_MODIFICATION_REQUEST_SEND_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 2 + iota
// 	NAS_5GSM_PDU_SESSION_MODIFICATION_REJECT_RECV_EVENT
// 	NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_RECV_EVENT
// 	NAS_5GSM_PDU_SESSION_MODIFICATION_COMPLETE_SEND_EVENT
// 	NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_REJECT_SEND_EVENT

// 	NAS_5GSM_PDU_SESSION_RELEASE_REQUEST_SEND_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 5 + iota
// 	NAS_5GSM_PDU_SESSION_RELEASE_REJECT_RECV_EVENT
// 	NAS_5GSM_PDU_SESSION_RELEASE_COMMAND_RECV_EVENT
// 	NAS_5GSM_PDU_SESSION_RELEASE_COMPLETE_SEND_EVENT

// 	NAS_5GSM_STATUS_SEND_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 6 + iota //214

// 	NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMMAND_RECV_EVENT = UE_5GS_SESSION_MANAGEMENT_EVENTS + 1 + iota //216
// 	NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMPLETE_SEND_EVENT
// 	NAS_5GSM_REMOTE_UE_REPORT_SEND_EVENT
// 	NAS_5GSM_REMOTE_UE_REPORT_RESPONSE_RECV_EVENT
// )

// Events between GNodeB and AMF (N2)
const N2_SEND_SDU_EVENT EventType = N2_EVENT + 0x0010000
const N2_RECV_SDU_EVENT EventType = N2_EVENT + 0x0020000

const (
	DOWNLINK_NAS_TRANSPORT_EVENT EventType = N2_EVENT + 1 + iota
	INITIAL_CTX_SETUP_REQUEST_EVENT
	NG_SETUP_RESPONSE_EVENT
	NG_SETUP_FAILURE_EVENT
	PDU_SESS_RESOURCE_SETUP_REQUEST_EVENT
	PDU_SESS_RESOURCE_RELEASE_COMMAND_EVENT
	UE_CTX_RELEASE_COMMAND_EVENT
)

// Events between GNodeB and UPF (N3)
const (
	DL_UE_DATA_TRANSPORT_EVENT EventType = N3_EVENT + 1 + iota
)

var evtStrMap map[EventType]string = map[EventType]string{
	INIT_EVENT:                                                                  "INIT-EVENT",
	QUIT_EVENT:                                                                  "QUIT-EVENT",
	ERROR_EVENT:                                                                 "ERROR-EVENT",
	DATA_PKT_GEN_REQUEST_EVENT:                                                  "DATA-PACKET-GENERATION-REQUEST-EVENT",
	DATA_PKT_GEN_SUCCESS_EVENT:                                                  "DATA-PACKET-SUCCESS-EVENT",
	DATA_PKT_GEN_FAILURE_EVENT:                                                  "DATA-PACKET-FAILURE-EVENT",
	CONNECTION_REQUEST_EVENT:                                                    "CONNECTION-REQUEST-EVENT",
	CONNECTION_RELEASE_REQUEST_EVENT:                                            "CONNECTION-RELEASE-REQUEST-EVENT",
	UL_INFO_TRANSFER_EVENT:                                                      "UL-INFO-TRANSFER-EVENT",
	DL_INFO_TRANSFER_EVENT:                                                      "DL-INFO-TRANSFER-EVENT",
	UL_UE_DATA_TRANSFER_EVENT:                                                   "UL-UE-DATA-TRANSFER-EVENT",
	DL_UE_DATA_TRANSFER_EVENT:                                                   "DL-UE-DATA-TRANSFER-EVENT",
	LAST_DATA_PKT_EVENT:                                                         "LAST-DATA-PACKET-EVENT",
	DATA_BEARER_SETUP_REQUEST_EVENT:                                             "DATA-BEARER-SETUP-REQUEST-EVENT",
	DATA_BEARER_SETUP_RESPONSE_EVENT:                                            "DATA-BEARER-SETUP-RESPONSE-EVENT",
	DATA_BEARER_RELEASE_REQUEST_EVENT:                                           "DATA-BEARER-RELEASE-REQUEST-EVENT",
	CTX_RELEASE_ACKNOWLEDGEMENT_EVENT:                                           "CONTEXT-RELEASE-ACKNOWLEDGEMENT-EVENT",
	TRIGGER_AN_RELEASE_EVENT:                                                    "TRIGGER-AN-RELEASE-EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_AUTHENTICATION_REQUEST:                         "NAS_5GMM_AUTHENTICATION_REQUEST_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_AUTHENTICATION_RESPONSE:                        "NAS_5GMM_AUTHENTICATION_RESPONSE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_AUTHENTICATION_RESPONSE:                          "NAS_5GMM_AUTHENTICATION_RESPONSE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_AUTHENTICATION_RESPONSE:                         "NAS_5GMM_AUTHENTICATION_RESPONSE_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_AUTHENTICATION_RESULT:                          "NAS_5GMM_AUTHENTICATION_RESULT_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_AUTHENTICATION_FAILURE:                         "NAS_5GMM_AUTHENTICATION_FAILURE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_AUTHENTICATION_FAILURE:                           "NAS_5GMM_AUTHENTICATION_FAILURE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_AUTHENTICATION_FAILURE:                          "NAS_5GMM_AUTHENTICATION_FAILURE_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_AUTHENTICATION_REJECT:                          "NAS_5GMM_AUTHENTICATION_REJECT_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_REGISTRATION_REQUEST:                           "NAS_5GMM_REGISTRATION_REQUEST_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_REGISTRATION_REQUEST:                             "NAS_5GMM_REGISTRATION_REQUEST_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_REGISTRATION_REQUEST:                            "NAS_5GMM_REGISTRATION_REQUEST_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_REGISTRATION_ACCEPT:                            "NAS_5GMM_REGISTRATION_ACCEPT_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_REGISTRATION_COMPLETE:                          "NAS_5GMM_REGISTRATION_COMPLETE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_REGISTRATION_COMPLETE:                            "NAS_5GMM_REGISTRATION_COMPLETE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_REGISTRATION_COMPLETE:                           "NAS_5GMM_REGISTRATION_COMPLETE_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_REGISTRATION_REJECT:                            "NAS_5GMM_REGISTRATION_REJECT_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_UL_NAS_TRANSPORT:                               "NAS_5GMM_UL_NAS_TRANSPORT_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_UL_NAS_TRANSPORT:                                 "NAS_5GMM_UL_NAS_TRANSPORT_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_UL_NAS_TRANSPORT:                                "NAS_5GMM_UL_NAS_TRANSPORT_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_DL_NAS_TRANSPORT:                               "NAS_5GMM_DL_NAS_TRANSPORT_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_DEREGISTRATION_REQUEST_UE_ORIG:                 "NAS_5GMM_DEREGISTRATION_REQUEST_UE_ORIG_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_DEREGISTRATION_REQUEST_UE_ORIG:                   "NAS_5GMM_DEREGISTRATION_REQUEST_UE_ORIG_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_DEREGISTRATION_REQUEST_UE_ORIG:                  "NAS_5GMM_DEREGISTRATION_REQUEST_UE_ORIG_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_DEREGISTRATION_ACCEPT_UE_ORIG:                  "NAS_5GMM_DEREGISTRATION_ACCEPT_UE_ORIG_RECV_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_DEREGISTRATION_REQUEST_UE_TERM:                 "NAS_5GMM_DEREGISTRATION_REQUEST_UE_TERM_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_DEREGISTRATION_ACCEPT_UE_TERM:                  "NAS_5GMM_DEREGISTRATION_ACCEPT_UE_TERM_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_DEREGISTRATION_ACCEPT_UE_TERM:                    "NAS_5GMM_DEREGISTRATION_ACCEPT_UE_TERM_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_DEREGISTRATION_ACCEPT_UE_TERM:                   "NAS_5GMM_DEREGISTRATION_ACCEPT_UE_TERM_ENCODED_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_SERVICE_REQUEST:                                "NAS_5GMM_SERVICE_REQUEST_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_SERVICE_REQUEST:                                  "NAS_5GMM_SERVICE_REQUEST_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_SERVICE_REQUEST:                                 "NAS_5GMM_SERVICE_REQUEST_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_SERVICE_ACCEPT:                                 "NAS_5GMM_SERVICE_ACCEPT_RECV_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_SERVICE_REJECT:                                 "NAS_5GMM_SERVICE_REJECT_RECV_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_CONFIGURATION_UPDATE:                           "NAS_5GMM_CONFIGURATION_UPDATE_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_CONFIGURATION_UPDATE_COMPLETE:                  "NAS_5GMM_CONFIGURATION_UPDATE_COMPLETE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_CONFIGURATION_UPDATE_COMPLETE:                    "NAS_5GMM_CONFIGURATION_UPDATE_COMPLETE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_CONFIGURATION_UPDATE_COMPLETE:                   "NAS_5GMM_CONFIGURATION_UPDATE_COMPLETE_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_IDENTITY_REQUEST:                               "NAS_5GMM_IDENTITY_REQUEST_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_IDENTITY_RESPONSE:                              "NAS_5GMM_IDENTITY_RESPONSE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_IDENTITY_RESPONSE:                                "NAS_5GMM_IDENTITY_RESPONSE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_IDENTITY_RESPONSE:                               "NAS_5GMM_IDENTITY_RESPONSE_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_NOTIFICATION:                                   "NAS_5GMM_NOTIFICATION_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_NOTIFICATION_RESPONSE:                          "NAS_5GMM_NOTIFICATION_RESPONSE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_NOTIFICATION_RESPONSE:                            "NAS_5GMM_NOTIFICATION_RESPONSE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_NOTIFICATION_RESPONSE:                           "NAS_5GMM_NOTIFICATION_RESPONSE_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_SECURITY_MODE_COMMAND:                          "NAS_5GMM_SECURITY_MODE_COMMAND_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_SECURITY_MODE_COMPLETE:                         "NAS_5GMM_SECURITY_MODE_COMPLETE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_SECURITY_MODE_COMPLETE:                           "NAS_5GMM_SECURITY_MODE_COMPLETE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_SECURITY_MODE_COMPLETE:                          "NAS_5GMM_SECURITY_MODE_COMPLETE_ENCODED_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_SECURITY_MODE_REJECT:                           "NAS_5GMM_SECURITY_MODE_REJECT_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_SECURITY_MODE_REJECT:                             "NAS_5GMM_SECURITY_MODE_REJECT_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_SECURITY_MODE_REJECT:                            "NAS_5GMM_SECURITY_MODE_REJECT_ENCODED_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_STATUS:                                         "NAS_5GMM_STATUS_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_STATUS:                                           "NAS_5GMM_STATUS_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_STATUS:                                          "NAS_5GMM_STATUS_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_STATUS:                                         "NAS_5GMM_STATUS_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_CONTROL_PLANE_SERVICE_REQUEST:                  "NAS_5GMM_CONTROL_PLANE_SERVICE_REQUEST_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_CONTROL_PLANE_SERVICE_REQUEST:                    "NAS_5GMM_CONTROL_PLANE_SERVICE_REQUEST_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_CONTROL_PLANE_SERVICE_REQUEST:                   "NAS_5GMM_CONTROL_PLANE_SERVICE_REQUEST_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMMAND:  "NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMMAND_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMPLETE: "NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMPLETE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMPLETE:   "NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMPLETE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMPLETE:  "NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_COMPLETE_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_RESULT:   "NAS_5GMM_NETWORK_SLICE_SPECIFIC_AUTHENTICATION_RESULT_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REQUEST:              "NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REQUEST_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REQUEST:                "NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REQUEST_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REQUEST:               "NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REQUEST_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_PDU_SESSION_ESTABLISHMENT_ACCEPT:               "NAS_5GSM_PDU_SESSION_ESTABLISHMENT_ACCEPT_RECV_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REJECT:               "NAS_5GSM_PDU_SESSION_ESTABLISHMENT_REJECT_RECV_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMMAND:             "NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMMAND_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMPLETE:            "NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMPLETE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMPLETE:              "NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMPLETE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMPLETE:             "NAS_5GSM_PDU_SESSION_AUTHENTICATION_COMPLETE_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_PDU_SESSION_AUTHENTICATION_RESULT:              "NAS_5GSM_PDU_SESSION_AUTHENTICATION_RESULT_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_REQUEST:               "NAS_5GSM_PDU_SESSION_MODIFICATION_REQUEST_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_REQUEST:                 "NAS_5GSM_PDU_SESSION_MODIFICATION_REQUEST_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_REQUEST:                "NAS_5GSM_PDU_SESSION_MODIFICATION_REQUEST_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_REJECT:                "NAS_5GSM_PDU_SESSION_MODIFICATION_REJECT_RECV_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND:               "NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_COMPLETE:              "NAS_5GSM_PDU_SESSION_MODIFICATION_COMPLETE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_COMPLETE:                "NAS_5GSM_PDU_SESSION_MODIFICATION_COMPLETE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_COMPLETE:               "NAS_5GSM_PDU_SESSION_MODIFICATION_COMPLETE_ENCODED_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_REJECT:        "NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_REJECT_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_REJECT:          "NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_REJECT_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_REJECT:         "NAS_5GSM_PDU_SESSION_MODIFICATION_COMMAND_REJECT_ENCODED_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_PDU_SESSION_RELEASE_REQUEST:                    "NAS_5GSM_PDU_SESSION_RELEASE_REQUEST_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_PDU_SESSION_RELEASE_REQUEST:                      "NAS_5GSM_PDU_SESSION_RELEASE_REQUEST_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_PDU_SESSION_RELEASE_REQUEST:                     "NAS_5GSM_PDU_SESSION_RELEASE_REQUEST_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_PDU_SESSION_RELEASE_REJECT:                     "NAS_5GSM_PDU_SESSION_RELEASE_REJECT_RECV_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_PDU_SESSION_RELEASE_COMMAND:                    "NAS_5GSM_PDU_SESSION_RELEASE_COMMAND_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_PDU_SESSION_RELEASE_COMPLETE:                   "NAS_5GSM_PDU_SESSION_RELEASE_COMPLETE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_PDU_SESSION_RELEASE_COMPLETE:                     "NAS_5GSM_PDU_SESSION_RELEASE_COMPLETE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_PDU_SESSION_RELEASE_COMPLETE:                    "NAS_5GSM_PDU_SESSION_RELEASE_COMPLETE_ENCODED_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_STATUS:                                         "NAS_5GSM_STATUS_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_STATUS:                                           "NAS_5GSM_STATUS_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_STATUS:                                          "NAS_5GSM_STATUS_ENCODED_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_STATUS:                                         "NAS_5GSM_STATUS_RECV_EVENT",
	N1_RECV_SDU_EVENT | NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMMAND:           "NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMMAND_RECV_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMPLETE:          "NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMPLETE_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMPLETE:            "NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMPLETE_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMPLETE:           "NAS_5GSM_SERVICE_LEVEL_AUTHENTICATION_COMPLETE_ENCODED_EVENT",
	N1_SEND_SDU_EVENT | NAS_5GSM_REMOTE_UE_REPORT:                               "NAS_5GSM_REMOTE_UE_REPORT_SEND_EVENT",
	N1_ENCODE_EVENT | NAS_5GSM_REMOTE_UE_REPORT:                                 "NAS_5GSM_REMOTE_UE_REPORT_ENCODE_REQ_EVENT",
	N1_ENCODED_EVENT | NAS_5GSM_REMOTE_UE_REPORT:                                "NAS_5GSM_REMOTE_UE_REPORT_ENCODED",
	N1_RECV_SDU_EVENT | NAS_5GSM_REMOTE_UE_REPORT_RESPONSE:                      "NAS_5GSM_REMOTE_UE_REPORT_RESPONSE_RECV_EVENT",
	N2_RECV_SDU_EVENT | NG_SETUP_RESPONSE_EVENT:                                 "NG_SETUP_RESPONSE_RECV_EVENT",
	N2_RECV_SDU_EVENT | NG_SETUP_FAILURE_EVENT:                                  "NG_SETUP_FAILURE_RECV_EVENT",
	N2_RECV_SDU_EVENT | DOWNLINK_NAS_TRANSPORT_EVENT:                            "DOWNLINK-NAS-TRANSPORT-RECV_EVENT",
	N2_RECV_SDU_EVENT | INITIAL_CTX_SETUP_REQUEST_EVENT:                         "INITIAL_CONTEXT_SETUP_REQUEST_RECV_EVENT",
	N2_RECV_SDU_EVENT:                     "N2_RECV_SDU_EVENT",
	N2_SEND_SDU_EVENT:                     "N2_SEND_SDU_EVENT",
	PDU_SESS_RESOURCE_SETUP_REQUEST_EVENT: "PDU_SESSION_RESOURCE_SETUP_REQUEST_EVENT",
	UE_CTX_RELEASE_COMMAND_EVENT:          "UE_CONTEXT_RELEASE_COMMAND_EVENT",
	DL_UE_DATA_TRANSPORT_EVENT:            "DL-UE-DATA-TRANSPORT-EVENT",
	PROC_START_EVENT:                      "PROC-START-EVENT",
	PROC_PASS_EVENT:                       "PROC-PASS-EVENT",
	PROC_FAIL_EVENT:                       "PROC-FAIL-EVENT",
}

func (id EventType) String() string {
	evtStr, ok := evtStrMap[id]
	if !ok {
		logger.AppLog.Fatalf("Cannot convert to string, Invalid Event ID: %#v", id)
	}
	return evtStr
}
