name: golangci-lint

on:
  push:
    branches:
      - ngap-tester
  pull_request:
    branches:
      - ngap-tester
    types: [ opened, reopened, synchronize ]

jobs:

  golangci-nas:
    if: github.repository_owner == 'openairinterface'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.29
